### ISSUE TITLE
How should the current data files be included?

### ISSUE THREAD

**Issue by ha0ye** [carpentries/instructor-feedback#3]
So `trainer-feedback-mockup.Rmd` tries to read in from https://raw.githubusercontent.com/kariljordan/assessment-fork/master/programmatic-assessment/instructor-training/data/2018-instructor-training-data.csv, which isn't available, and 
`2018-07-learners-pre-post-surveys.Rmd` tries to read in from 
the `../data/20180511_dcpre.csv` local file.

Neither of these work, and it looks like the files in the `data` folder here are structured a bit differently...

I'm a little lost on what data files to use, and how they should be coordinated.

**Comment by katrinleinweber** [comment]
This seems to be a result of https://github.com/carpentries/assessment/pull/217/ plus copy-pasting the code from that repo to here, instead of [forking it](https://github.com/carpentries/instructor-development/issues/70#issuecomment-426703429).

**Comment by katrintirok** [comment]
I am working on the data files in the data folder, one file per question for instructor feedback (not trainer feedback).

**Comment by kariljordan** [comment]
@ha0ye the trainer feedback file was an example to just visually look at as an option for what the "dashboard"/report would look like. All of the files that we need to work on are in the data folder of this repo.
