### ISSUE TITLE
Project: Instructor Feedback Reports

### ISSUE THREAD

**Issue by kariljordan** [carpentries/instructor-feedback#4]
Currently, instructors receive a SurveyMonkey link with their pre- and post-workshop survey results. This document, though useful, does not provide a way for instructors to understand the results of their surveys, or opportunities to improve if there scores are sub-optimal.

The instructor development committee has agreed to take on a project to create feedback reports for our instructors that will serve as a resource to help them improve (where needed) and congratulate them on their teaching.

I created a [mock report](https://carpentries.github.io/assessment/programmatic-assessment/instructor-training/trainer-feedback-reports/trainer_report_mockup.html) in R. Keep in mind this mockup uses data from the trainer post workshop surveys. Once we have feedback reports for the instructors, we'd also like to create them for instructor trainers.

We'd like to use [R Shiny](https://shiny.rstudio.com).

**We want 2-3 community members to help with this project.**

**Project Outline:**

- [ ] Identify specifications to include in the [post-workshop survey](https://www.surveymonkey.com/r/swc_post_workshop_v1?workshop_id=[workshop_id_value]) report for instructors.
- [ ] Create a ‘how to interpret your report’ document to send along with instructor feedback report.
- [ ] Create/revise a [mock-up script](https://carpentries.github.io/assessment/programmatic-assessment/instructor-training/trainer-feedback-reports/trainer_report_mockup.html) for the Instructor Feedback Report.
- [ ] Set up automation for the script and report generation.
- [ ] Get feedback from the community about the look and feel of the report.
- [ ] Identify resources for coaching to supplement the report.
- [ ] Write a blog post to launch the reports.

**Timeline**

- This project will begin September 24th, and we'd like to have it complete by November 30th.

**Action Required**
- If you have thoughts about the project and/or ideas, please comment on this issue.
- If you are interested in actively participating in this project (contributing code, etc.), please [e-mail Kari](mailto:kariljordan@carpentries.org) and comment below by **September 24th**.

**Comment by kariljordan** [comment]
No worries @mfoos. Feel free to disable any notifications from this thread so you aren't bombarded. I received the data files from @fmichonneau and created a [new repo](https://github.com/carpentries/instructor-feedback) under the carpentries organization so that we don't mess up anything in the assessment repo. @katrinleinweber @katrintirok and @ha0ye should have received invitations to join. I will add the data files, surveys, and code there and we can get to work.

@katrinleinweber your summary is spot on. SurveyMonkey does provide data trends like this:
<img width="888" alt="screen shot 2018-10-03 at 11 19 04 am" src="https://user-images.githubusercontent.com/21027863/46420666-8c249280-c6fe-11e8-9314-e9d1ff91f748.png">

**Comment by kariljordan** [comment]
@katrintirok we are happy to announce that @fmichonneau is ready to release the instructor feedback reports! Your shiny app was **EXTREMELY** useful for us and gave us ideas to incorporate. We weren’t able to use the EXACT R code you created because of privacy concerns. The code for the app is in a private repo because there are a few sensitive things to make sure nobody can access the results. @fmichonneau would like to include you in the acknowledgements, so let us know if you're fine with that. THANK YOU!

**Comment by katrintirok** [comment]
Hi Kari,
That sounds great, I am keen to see the new reports. I am fine with being
included in the acknowledgements. Sorry for the late reply, unfortunately I
don't have as much time for the carpentries at the moment.
Best regards
Katrin
